<a href="https://colab.research.google.com/github/basharE/ML_course/blob/main/page64_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Question 1


In [ ]:
import numpy as np
z = np.linspace(0, 9, 10)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



# Question 2

In [ ]:
import numpy as np
k = np.ones((3, 3), dtype=bool)
print(k)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Question 3

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
m = arr % 2 != 0
s = arr[m]
print(s)

[1 3 5 7 9]



# Question 4

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = a == b
n = a[c]
print(n)

[2 2 4 4]


# Question 5

In [ ]:
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='float')
print("mean: ", np.mean(iris[:,0]))
print("median: ", np.median(iris[:,0]))
print("standard deviation: ", np.std(iris[:,0]))

mean:  5.843333333333334
median:  5.8
standard deviation:  0.8253012917851409


# Question 6

In [ ]:
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='object')
arr = iris[:,2]
i = 0
while i < arr.size:
    if(i==arr.size):
        break
    if float(arr[i]) < 3:
        arr[i]='small'
    elif float(arr[i]) >= 5:
        arr[i]='large'
    elif 3 <= float(arr[i]) < 5:
        arr[i]='medium'
    i = i+1
iris[:,2]=arr 
print(iris)

[[b'5.1' b'3.5' 'small' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' 'small' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' 'small' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' 'small' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' 'small' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' 'small' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' 'small' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' 'small' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' 'small' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' 'small' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' 'small' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' 'small' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' 'small' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' 'small' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' 'small' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' 'small' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' 'small' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' 'small' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' 'small' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' 'small' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' 'small' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.